modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved" # https://choosealicense.com/


# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues"

[[mods]]
modId = "kuberest"
version = "${version}"
displayName = "KubeREST"
logoFile="icon.png"
credits="Thanks to FooterMan for the KubeJS Addon Template!"
authors="Bluemethyst"
description = '''
A KubeJS addon for hosting webservers!.
'''

[[dependencies.kuberest]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kuberest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kuberest]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
